### ISSUE TITLE
ValueError: Variable Embedding already exists

### ISSUE THREAD

**Issue by diaoxue** [brightmart/text_classification#14]
Traceback (most recent call last):
  File "p5_fastTextB_train.py", line 163, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "p5_fastTextB_train.py", line 76, in main
    fast_text=fastText(FLAGS.label_size, FLAGS.learning_rate, FLAGS.batch_size, FLAGS.decay_steps, FLAGS.decay_rate,FLAGS.num_sampled,FLAGS.sentence_len,vocab_size,FLAGS.embed_size,FLAGS.is_training)
  File "/home/defy/text_classification-master/a01_FastText/p5_fastTextB_model.py", line 29, in __init__
    self.instantiate_weights()
  File "/home/defy/text_classification-master/a01_FastText/p5_fastTextB_model.py", line 42, in instantiate_weights
    self.Embedding = tf.get_variable("Embedding", [self.vocab_size, self.embed_size])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 356, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 653, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable Embedding already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/home/defy/text_classification-master/a01_FastText/p5_fastTextB_model.py", line 42, in instantiate_weights
    self.Embedding = tf.get_variable("Embedding", [self.vocab_size, self.embed_size])
  File "/home/defy/text_classification-master/a01_FastText/p5_fastTextB_model.py", line 29, in __init__
    self.instantiate_weights()
  File "/home/defy/text_classification-master/a01_FastText/p5_fastTextB_model.py", line 104, in test
    fastText=fastTextB(num_classes, learning_rate, batch_size, decay_steps, decay_rate,5,sequence_length,vocab_size,embed_size,is_training)

python 2.7 ,tensorlfow 1.1, run p5_fastTextB_model, but get this error @brightmart

**Comment by brightmart** [comment]
now this problem can be solved by comment out invoke of test function in the model:
test()--->//test()
