### ISSUE TITLE
not found data file

### ISSUE THREAD

**Issue by doubleycn** [brightmart/text_classification#15]
```bash
hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
('cache_path:', 'cache_vocabulary_label_pik/_word_voabulary.pik', 'file_exists:', False)
('create vocabulary. word2vec_model_path:', 'zhihu-word2vec-title-desc.bin-100')
Traceback (most recent call last):
  File "p5_fastTextB_train.py", line 161, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "p5_fastTextB_train.py", line 44, in main
    vocabulary_word2index, vocabulary_index2word = create_voabulary()
  File "../aa1_data_util/data_util_zhihu.py", line 26, in create_voabulary
    model=word2vec.load(word2vec_model_path,kind='bin')
  File "/usr/lib64/python2.7/site-packages/word2vec/io.py", line 18, in load
    return word2vec.WordVectors.from_binary(fname, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/word2vec/wordvectors.py", line 154, in from_binary
    with open(fname, 'rb') as fin:
IOError: [Errno 2] No such file or directory: 'zhihu-word2vec-title-desc.bin-100'
```
please help.

**Comment by lydemo** [comment]
I also meet the same problem as yours...

**Comment by brightmart** [comment]
please find it in:
https://github.com/brightmart/text_classification/issues/3
