### ISSUE TITLE
pickle.UnpicklingError: could not find MARK

### ISSUE THREAD

**Issue by xupengrun** [brightmart/text_classification#26]
Hi @brightmart 
When i run the fasttext train script on windows or centos machine, I've got these errors  "pickle.UnpicklingError: could not find MARK", it puzzled me a few days,please help me

D:\Anaconda3\python.exe D:/text_classification/a01_FastText/p6_fastTextB_train_multilabel.py
started...
ended...
D:\Anaconda3\lib\site-packages\gensim\utils.py:862: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Traceback (most recent call last):
  File "D:/text_classification/a01_FastText/p6_fastTextB_train_multilabel.py", line 192, in <module>
    tf.app.run()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:/text_classification/a01_FastText/p6_fastTextB_train_multilabel.py", line 38, in main
    vocabulary_word2index, vocabulary_index2word = create_voabulary()
  File "D:\text_classification\aa1_data_util\data_util_zhihu.py", line 31, in create_voabulary
    model = Word2Vec.load(word2vec_model_path)
  File "D:\Anaconda3\lib\site-packages\gensim\models\word2vec.py", line 1483, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\gensim\utils.py", line 282, in load
cache_path: cache_vocabulary_label_pik/_word_voabulary.pik file_exists: False
create vocabulary. word2vec_model_path: ../data/zhihu-word2vec-title-desc.bin-100
    obj = unpickle(fname)
  File "D:\Anaconda3\lib\site-packages\gensim\utils.py", line 935, in unpickle
    return _pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: could not find MARK

**Comment by brightmart** [comment]
hi. this is releted to operation system, nerver see this before. 
you can install word2vec properly first or remove word2vec if you dont want to use pretrained word embedding.

by the way,why you choose fastest model?
________________________________________
发件人: xupeng [notifications@github.com]
发送时间: 2017年12月21日 17:04
收件人: brightmart/text_classification
抄送: brightmart; Mention
主题: [brightmart/text_classification] pickle.UnpicklingError: could not find MARK (#26)

Hi @brightmart<https://github.com/brightmart>
When i run the train script on windows or centos machine, I've got these errors "pickle.UnpicklingError: could not find MARK", it puzzled me a few days,please help me

D:\Anaconda3\python.exe D:/text_classification/a01_FastText/p6_fastTextB_train_multilabel.py
started...
ended...
D:\Anaconda3\lib\site-packages\gensim\utils.py:862: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Traceback (most recent call last):
File "D:/text_classification/a01_FastText/p6_fastTextB_train_multilabel.py", line 192, in
tf.app.run()
File "D:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "D:/text_classification/a01_FastText/p6_fastTextB_train_multilabel.py", line 38, in main
vocabulary_word2index, vocabulary_index2word = create_voabulary()
File "D:\text_classification\aa1_data_util\data_util_zhihu.py", line 31, in create_voabulary
model = Word2Vec.load(word2vec_model_path)
File "D:\Anaconda3\lib\site-packages\gensim\models\word2vec.py", line 1483, in load
model = super(Word2Vec, cls).load(*args, **kwargs)
File "D:\Anaconda3\lib\site-packages\gensim\utils.py", line 282, in load
cache_path: cache_vocabulary_label_pik/_word_voabulary.pik file_exists: False
create vocabulary. word2vec_model_path: ../data/zhihu-word2vec-title-desc.bin-100
obj = unpickle(fname)
File "D:\Anaconda3\lib\site-packages\gensim\utils.py", line 935, in unpickle
return _pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: could not find MARK

―

**Comment by xupengrun** [comment]
Thx,I h've solved this error,At first i import the word2vec from the gensim package,it dosen't work,I try to install word2vec by command pip install word2vec in linux os,it works.
I choose fasttext model for test
